name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! This looks like your first issue here. THanks for contributing.'
        pr-message: 'Hi there! Looks like this is your first PR here. Thanks for contributing.'
